<a href="https://colab.research.google.com/github/shukaracharya/Asignment/blob/main/Numpy_Assign.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
############ Qustion 1 ################
##########  Create a null vector of size 10 but the fifth value which is 1. #########
import numpy as np
x=np.zeros(10)
x[4]=1
print(x)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [5]:
############ Qustion 2 ################
######### Create a vector with values ranging from 10 to 49.############
v= np.arange(10,49)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [10]:
############ Qustion 3 ################
########  Create a 3x3 matrix with values ranging from 0 to 8 ############
c=np.arange(0, 9).reshape((3,3))
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
############ Qustion 4 ################
######## Find indices of non-zero elements from [1,2,0,0,4,0] ######
b=np.array([1,2,0,0,4,0])
c=np.nonzero(b)
print(c)


(array([0, 1, 4]),)


In [28]:
############ Qustion 5 ################
########Create a 10x10 array with random values and find the minimum and maximum values. #######
x=np.random.random((10,10))
print(x)
xmin=x.min()
print("Minimum In Matrix = ", xmin)
xmax=x.max()
print("Maximum In Matrix = ", xmax)

[[0.98146228 0.70758672 0.53804518 0.84058035 0.8347095  0.96183354
  0.32948354 0.73353436 0.29011908 0.89262412]
 [0.52897504 0.94820848 0.11805031 0.39392962 0.14502157 0.72066886
  0.41027121 0.84098394 0.7205817  0.03487028]
 [0.13816967 0.08010111 0.36917686 0.81651991 0.94563748 0.49733838
  0.00763866 0.70542112 0.35337458 0.43885206]
 [0.91059701 0.50061982 0.29269678 0.86106396 0.76044134 0.56289347
  0.12833133 0.63683617 0.80582177 0.56817871]
 [0.5033249  0.6191237  0.37191807 0.56593099 0.56598477 0.69490267
  0.77491724 0.88580557 0.57993663 0.69372774]
 [0.54475483 0.82192712 0.30929857 0.08241009 0.66410621 0.17328234
  0.18244582 0.51134037 0.42396376 0.34331671]
 [0.23655611 0.92013729 0.93017834 0.89812721 0.95855309 0.58954639
  0.39941261 0.17993886 0.27728787 0.81987538]
 [0.12171348 0.98848954 0.42237626 0.26745728 0.10838731 0.64593465
  0.80255287 0.02526645 0.28513316 0.78567463]
 [0.50667474 0.05856807 0.57132257 0.93956918 0.88759273 0.67146791
  0.3591979 

In [27]:
############ Qustion 6 ################
####### Create a random vector of size 30 and find the mean value. ########
z=np.random.random(30)
print(z)
y=z.mean()
print("Mean Value Of Vector =",y)

[0.68872972 0.88304711 0.52314841 0.96562916 0.77987885 0.52203866
 0.37680572 0.92792675 0.47736664 0.37365935 0.52892133 0.60980627
 0.09168696 0.55267965 0.20318035 0.54364445 0.96163736 0.30929627
 0.56916784 0.35168435 0.80702687 0.78848996 0.81948823 0.32526016
 0.33213976 0.85949502 0.22641582 0.7137245  0.9057896  0.62065779]
Mean Value Of Vector = 0.5879474301989579
